name: DebugBuild
on: 
  push:
    branches:
      - master
env:
  # ソリューションファイルのパスを正確に指定
  SOLUTION_FILE_PATH: project/DirectXGame.sln
  CONFIGURATION: Debug
jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Build the project
        run: |
          if [ ! -f "${{env.SOLUTION_FILE_PATH}}" ]; then
            echo "Error: Solution file not found!"
            exit 1
          fi
          msbuild ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}}
